packages:
  - '.'
overrides:
  '@hono/node-server': '>=1.19.13'
publicHoistPattern:
  - '*'
packageImportMethod: clone-or-copy
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@swc/core': true
  esbuild: true
  lefthook: true
  prisma: true
